generatorOptions:
 disableNameSuffixHash: true
secretGenerator:
  - name: app-mysql-pass
    namespace: app
    literals:
    - password=ASuperSecurePassword
  - name: db-mysql-pass
    namespace: database
    literals:
    - password=NRwcxaDffgBxmfVT3piZtsPqrHb
  - name: grafana
    namespace: observability
    literals:
    - admin-username=grafana
    - admin-password=NRwcxaDffgBxmfVT3piZtsPqrHb
resources:
  - database/mysql-deployment.yaml
  - app/wordpress-deployment.yaml
  - app/ingress.yaml
  - frontend/cert-manager-prod.yaml
  - frontend/cert-manager.yaml
  - frontend/nginx-ingress.yaml
  - monitoring/prometheus-rbac.yaml
  - monitoring/config-map.yaml
  - monitoring/prometheus.yaml
  - monitoring/blackbox.yaml
  - observability/grafana-import.yaml
  - observability/configmap.yaml
  - observability/grafana.yaml
  - observability/ingress.yaml
patchesStrategicMerge:
  - your-info.yml 
