apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: letsencrypt@falconsupport.com
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: wordpress
  namespace: app
spec:
  rules:
  - host: wordpress-1.k8s.personal.andyrepton.com
    http:
      paths:
      - backend:
          serviceName: wordpress
          servicePort: 80
        path: /
  tls:
  - hosts:
    - wordpress-1.k8s.personal.andyrepton.com
    secretName: wordpress-cert
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: grafana
  namespace: observability
spec:
  rules:
  # Edit the following to fit your domain name
  - host: grafana.k8s.personal.andyrepton.com
    http:
      paths:
      - backend:
          serviceName: grafana
          servicePort: 3000
        path: /
  tls:
  - hosts:
    - grafana.k8s.personal.andyrepton.com
    secretName: grafana-cert
